Revert of [BackgroundSync] Launch the browser on Android when next online (patchset #17 id:340001 of https://codereview.chromium.org/1140813006/)
Reason for revert:
Unused variable breaks CrOS build:

http://build.chromium.org/p/chromium.chromiumos/builders/ChromiumOS%20daisy%20Compile/builds/83/steps/compile/logs/stdio

../../content/browser/background_sync/background_sync_manager.cc: In member function 'void content::BackgroundSyncManager::SchedulePendingRegistrations()':
../../content/browser/background_sync/background_sync_manager.cc:650:8: error: variable 'keep_browser_alive_for_one_shot' set but not used [-Werror=unused-but-set-variable]
   bool keep_browser_alive_for_one_shot = false;
        ^
cc1plus.elf: all warnings being treated as errors

Original issue's description:
> [BackgroundSync] Launch the browser on Android when next online
>
> On Android devices BackgroundSync needs to launch the browser the next time the device goes online if a one-shot sync is registered. This CL adds an Android Receiver and Service (BackgroundSyncLauncherService) to listen to connectvity events and launch the browser. It also provides a BackgroundSyncLauncher JNI class that C++ can interact with to register interest in launching in the background.
>
> This feature is experimental and behind a flag.
>
> Note that the components_tests.gyp change (to add content_java) is because content::StoragePartition creates a BackgroundSyncManager which immediately talks to java therefore the content java classes are needed for testing.
>
> BUG=479665
>
> Committed: https://crrev.com/6970b0ad59723ced9cc473f5474e8c3c0bf5d7bc
> Cr-Commit-Position: refs/heads/master@{#331826}

TBR=jochen@chromium.org,jdduke@chromium.org,mvanouwerkerk@chromium.org,nyquist@chromium.org,peter@chromium.org,tedchoc@chromium.org,jkarlin@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=479665

Review URL: https://codereview.chromium.org/1149373007

Cr-Commit-Position: refs/heads/master@{#331836}